"""SQLAlchemy 2.0 ORM models / metadata for the marketplace persistence layer.

This module is the **single source of truth for the database schema metadata**
(design.md -> "Stable domain data, versioned at the edges" and "Data Models").
Alembic migrations are wired to :data:`Base.metadata` as their ``target_metadata``
so future migrations (tasks 3.2 / 3.3 / 3.5) can be autogenerated or hand-written
against a consistent picture of the schema.

Task 3.1 establishes the first slice of the schema only:

  * ``meta``        - single-row table holding the ``schema_version`` (Req 13.7).
  * ``users``       - channel-neutral identity, role, offline-payment flag, and
                      the per-user ``language_preference`` (Req 1.6, 17.1, 18.x).
  * ``categories``  - case-insensitive-unique product groups (Req 2.8, 2.11).
  * ``products``    - catalog items with range CHECK constraints (Req 2.5-2.9).

Carts, orders, payments, audit, notifications and seller settings are
intentionally *not* defined here; they arrive in later migrations.

Portability: the models use SQLAlchemy generic types (``Uuid``, ``Numeric``,
``DateTime(timezone=True)``, ``Enum``) that render natively on PostgreSQL
(runtime) and degrade cleanly on SQLite (local/dev/test) - e.g. native ``ENUM``
types on PostgreSQL become ``VARCHAR`` + ``CHECK`` on SQLite, and ``UUID``
becomes ``CHAR(32)``.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Optional

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ---------------------------------------------------------------------------
# Constraint/index naming convention.
#
# A deterministic naming convention keeps constraint and index names identical
# between the ORM metadata and the hand-written Alembic migration, and lets
# Alembic autogenerate produce stable names for tasks 3.2 / 3.3 / 3.5.
# ---------------------------------------------------------------------------
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base carrying the shared, conventionally-named metadata."""

    metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)


# ---------------------------------------------------------------------------
# Enumerations (design.md -> Data Models).
#
# Member name == stored value for every enum, so storage is identical whether
# resolved by name or value. ``*_VALUES`` tuples are re-used verbatim by the
# Alembic migration to guarantee the migration and the ORM agree on the exact
# label set and ``name`` of each enum type.
# ---------------------------------------------------------------------------
class Role(str, enum.Enum):
    """Account role. ADMIN is reserved for the configured Seller (Req 1.6)."""

    ADMIN = "ADMIN"
    CUSTOMER = "CUSTOMER"


class Unit(str, enum.Enum):
    """Sale unit for a product (Req 2.7, Assumption A1)."""

    KILOGRAM = "KILOGRAM"
    QUINTAL = "QUINTAL"
    BAG = "BAG"


class OrderState(str, enum.Enum):
    """Order lifecycle states (design.md -> state machine).

    Defined now so the ``order_state`` enum type exists from the initial
    migration; the ``orders`` table that uses it is created in task 3.2.
    """

    PLACED = "PLACED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    APPROVED = "APPROVED"
    READY_FOR_PICKUP = "READY_FOR_PICKUP"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class Language(str, enum.Enum):
    """Presentation language preference (Req 18). NULL/unset -> Hindi default."""

    HI = "HI"
    EN = "EN"


class AuditAction(str, enum.Enum):
    """Significant, audited Seller actions (design.md -> Audit_Trail; Req 15.12,
    17.8).

    The set is intentionally **extensible**: new audited actions are added as
    additive enum members (PostgreSQL ``ALTER TYPE ... ADD VALUE`` / a fresh
    CHECK on SQLite) without breaking older append-only rows.
    """

    MODIFY_LINE = "MODIFY_LINE"
    ADD_LINE = "ADD_LINE"
    REMOVE_LINE = "REMOVE_LINE"
    OFFLINE_APPROVAL = "OFFLINE_APPROVAL"


class NotificationKind(str, enum.Enum):
    """Kind of notification enqueued for delivery (design.md -> Notifications;
    Req 11). Extensible/additive as new notification categories appear."""

    STATE_CHANGE = "STATE_CHANGE"
    NEW_ORDER = "NEW_ORDER"
    MODIFIED = "MODIFIED"


class NotificationStatus(str, enum.Enum):
    """Delivery lifecycle of a notification row (Req 11.3, 11.4, 11.5).

    PENDING/FAILED rows are due for (re)delivery; DELIVERED is terminal-success;
    UNDELIVERED is terminal-failure after the bounded retry budget is exhausted.
    """

    PENDING = "PENDING"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    UNDELIVERED = "UNDELIVERED"


ROLE_VALUES: tuple[str, ...] = tuple(m.value for m in Role)
UNIT_VALUES: tuple[str, ...] = tuple(m.value for m in Unit)
ORDER_STATE_VALUES: tuple[str, ...] = tuple(m.value for m in OrderState)
LANGUAGE_VALUES: tuple[str, ...] = tuple(m.value for m in Language)
AUDIT_ACTION_VALUES: tuple[str, ...] = tuple(m.value for m in AuditAction)
NOTIFICATION_KIND_VALUES: tuple[str, ...] = tuple(m.value for m in NotificationKind)
NOTIFICATION_STATUS_VALUES: tuple[str, ...] = tuple(m.value for m in NotificationStatus)

# Canonical enum type names (shared with the migration).
ORDER_STATE_ENUM_NAME = "order_state"
UNIT_ENUM_NAME = "unit"
ROLE_ENUM_NAME = "role"
LANGUAGE_ENUM_NAME = "language"
AUDIT_ACTION_ENUM_NAME = "audit_action"
NOTIFICATION_KIND_ENUM_NAME = "notification_kind"
NOTIFICATION_STATUS_ENUM_NAME = "notification_status"

# Numeric range bounds from the design / Req 2.5, 2.6, 2.9.
PRICE_MAX = "9999999.99"
QUANTITY_MAX = "9999999"

# Default UTR acceptance pattern for the Seller-configurable UTR format
# (design.md -> Seller_Settings / Configuration; Req 6.2/6.6): exactly 12
# alphanumeric characters. Shared verbatim with the Alembic migration so the
# ORM metadata and the migration agree on the server_default literal.
DEFAULT_UTR_PATTERN = "^[A-Za-z0-9]{12}$"


def _enum(py_enum: type[enum.Enum], name: str) -> sa.Enum:
    """Build a portable :class:`sqlalchemy.Enum` storing the member *values*.

    ``create_constraint=True`` makes SQLite (which has no native ENUM) enforce
    the allowed value set via a CHECK constraint, mirroring the native ENUM
    enforcement PostgreSQL gives for free.
    """
    return sa.Enum(
        py_enum,
        name=name,
        native_enum=True,  # native ENUM on PostgreSQL; VARCHAR+CHECK on SQLite
        create_constraint=True,
        values_callable=lambda e: [m.value for m in e],
    )


def _json() -> sa.types.TypeEngine:
    """Build a portable JSON column type.

    Renders as ``JSONB`` on PostgreSQL (binary, indexable) and as generic
    ``JSON`` (stored as TEXT) on SQLite, per design.md ("use JSONB on Postgres,
    JSON on SQLite"). Used for the audit ``detail`` and notification ``payload``
    documents, both of which embed a ``format_version`` so the payload formats
    stay additively versioned (Req 13.7).
    """
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


class Meta(Base):
    """Single-row table recording the persisted schema version (Req 13.7)."""

    __tablename__ = "meta"
    __table_args__ = (sa.CheckConstraint("meta_id = 1", name="singleton"),)

    meta_id: Mapped[int] = mapped_column(sa.Integer, primary_key=True, default=1)
    schema_version: Mapped[int] = mapped_column(sa.Integer, nullable=False)


class User(Base):
    """Channel-neutral user identity (design.md -> Data Models -> Users)."""

    __tablename__ = "users"

    user_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    # External identity (Telegram); other channels (WhatsApp, ...) added later.
    telegram_user_id: Mapped[int] = mapped_column(
        sa.BigInteger, nullable=False, unique=True
    )
    # Phone number from Share Contact; PII, encrypted at rest by the app layer.
    verified_contact: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    # NULL until the shared contact is verified; unverified users cannot order.
    contact_verified_at: Mapped[Optional[datetime]] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    role: Mapped[Role] = mapped_column(_enum(Role, ROLE_ENUM_NAME), nullable=False)
    offline_payment_allowed: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.false()
    )
    # NULL/unset -> treated as the Hindi default by the renderer (Req 18.2/18.4).
    language_preference: Mapped[Optional[Language]] = mapped_column(
        _enum(Language, LANGUAGE_ENUM_NAME), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


class Category(Base):
    """Product category with a case-insensitive-unique name (Req 2.8, 2.11)."""

    __tablename__ = "categories"
    __table_args__ = (
        sa.CheckConstraint(
            "length(name) >= 1 AND length(name) <= 50", name="name_len"
        ),
        # Case-insensitive uniqueness via a functional unique index on lower(name).
        sa.Index("uq_categories_name_lower", sa.func.lower(sa.column("name")), unique=True),
    )

    category_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


class Product(Base):
    """Catalog product with range CHECK constraints (Req 2.5, 2.6, 2.9)."""

    __tablename__ = "products"
    __table_args__ = (
        sa.CheckConstraint(
            "length(name) >= 1 AND length(name) <= 100", name="name_len"
        ),
        sa.CheckConstraint(
            "description IS NULL OR length(description) <= 1000",
            name="description_len",
        ),
        sa.CheckConstraint(
            f"price_per_unit >= 0 AND price_per_unit <= {PRICE_MAX}",
            name="price_range",
        ),
        sa.CheckConstraint(
            f"min_order_quantity > 0 AND min_order_quantity <= {QUANTITY_MAX}",
            name="moq_range",
        ),
        sa.CheckConstraint(
            f"stock_quantity >= 0 AND stock_quantity <= {QUANTITY_MAX}",
            name="stock_range",
        ),
        # Defense-in-depth non-negative stock guard (task 3.1 detail / Req 7.4).
        sa.CheckConstraint("stock_quantity >= 0", name="stock_non_negative"),
        # Browsing indexes.
        sa.Index("ix_products_category_id_available", "category_id", "available"),
        sa.Index(
            "ix_products_available_partial",
            "category_id",
            postgresql_where=sa.text("available"),
            sqlite_where=sa.text("available"),
        ),
    )

    product_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(sa.Text, nullable=False)
    category_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("categories.category_id"), nullable=False
    )
    description: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    unit: Mapped[Unit] = mapped_column(_enum(Unit, UNIT_ENUM_NAME), nullable=False)
    price_per_unit: Mapped[float] = mapped_column(sa.Numeric(12, 2), nullable=False)
    min_order_quantity: Mapped[float] = mapped_column(sa.Numeric(12, 3), nullable=False)
    stock_quantity: Mapped[float] = mapped_column(sa.Numeric(12, 3), nullable=False)
    available: Mapped[bool] = mapped_column(
        sa.Boolean, nullable=False, server_default=sa.true()
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


# ---------------------------------------------------------------------------
# Carts and Cart_Items (task 3.2; design.md -> Data Models -> Carts/Cart_Items).
#
# One active cart per customer (UNIQUE customer_id); a cart line is unique per
# (cart_id, product_id) so re-adding a product combines quantities on add rather
# than creating a duplicate line (Req 4.5).
# ---------------------------------------------------------------------------
class Cart(Base):
    """A customer's single active cart (one per customer, Req 4.5)."""

    __tablename__ = "carts"

    cart_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    # One active cart per customer -> UNIQUE FK to users.
    customer_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("users.user_id"), nullable=False, unique=True
    )


class CartItem(Base):
    """A single product line within a cart (Req 4.5)."""

    __tablename__ = "cart_items"
    __table_args__ = (
        # Combine-on-add: at most one line per product in a given cart (Req 4.5).
        sa.UniqueConstraint("cart_id", "product_id"),
    )

    cart_item_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    cart_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("carts.cart_id"), nullable=False
    )
    product_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("products.product_id"), nullable=False
    )
    # Validated against MOQ/current stock at the service layer (Req 4.x).
    quantity: Mapped[float] = mapped_column(sa.Numeric(12, 3), nullable=False)


# ---------------------------------------------------------------------------
# Orders and Order_Items (task 3.2; design.md -> Data Models -> Orders).
#
# ``order_number`` is a human-friendly serial id (BIGINT IDENTITY on PostgreSQL;
# the column is plain BIGINT on SQLite where the app/tests supply the value).
# ``state`` reuses the ``order_state`` enum type created in migration 0001 -
# it is NOT recreated here. Per-line ``unit_price`` snapshots the catalog price
# at order time so later price edits never change historical totals.
# ---------------------------------------------------------------------------
class Order(Base):
    """An placed order with lifecycle ``state`` and snapshot totals (Req 5)."""

    __tablename__ = "orders"
    __table_args__ = (
        sa.CheckConstraint(
            "rejection_reason IS NULL OR length(rejection_reason) <= 500",
            name="rejection_reason_len",
        ),
        # History listing: newest-first per customer (Req 10.1). The migration
        # emits ``created_at DESC``; SQLite reflection drops sort order and
        # alembic compares indexes by column membership, so the model lists the
        # plain columns to keep ``alembic check`` drift-free across backends.
        sa.Index(
            "ix_orders_customer_id_created_at",
            "customer_id",
            "created_at",
        ),
        # Active-order listing by state then time (Req 10.6).
        sa.Index("ix_orders_state_created_at", "state", "created_at"),
    )

    order_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    # Human-friendly serial id (BIGSERIAL/IDENTITY on PostgreSQL). UNIQUE.
    order_number: Mapped[int] = mapped_column(
        sa.BigInteger, sa.Identity(), nullable=False, unique=True
    )
    customer_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("users.user_id"), nullable=False
    )
    state: Mapped[OrderState] = mapped_column(
        _enum(OrderState, ORDER_STATE_ENUM_NAME), nullable=False
    )
    total_amount: Mapped[float] = mapped_column(sa.Numeric(12, 2), nullable=False)
    rejection_reason: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    schema_version: Mapped[int] = mapped_column(
        sa.SmallInteger, nullable=False, server_default=sa.text("1")
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


class OrderItem(Base):
    """A single product line within an order with a price snapshot (Req 5.2)."""

    __tablename__ = "order_items"
    __table_args__ = (
        # Fulfillability recompute scans order lines by product (Req 16.1).
        sa.Index("ix_order_items_product_id", "product_id"),
    )

    order_item_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    order_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("orders.order_id"), nullable=False
    )
    product_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("products.product_id"), nullable=False
    )
    ordered_quantity: Mapped[float] = mapped_column(sa.Numeric(12, 3), nullable=False)
    # Snapshot of the product's unit price at order time (Req 5.2).
    unit_price: Mapped[float] = mapped_column(sa.Numeric(12, 2), nullable=False)
    # = ordered_quantity x unit_price, rounded via Monetary_Rounding (Req 5.2).
    line_amount: Mapped[float] = mapped_column(sa.Numeric(12, 2), nullable=False)


# ---------------------------------------------------------------------------
# Payments (task 3.3; design.md -> Data Models -> Payments).
#
# Exactly one payment per order (UNIQUE ``order_id``). ``utr`` is variable-length
# TEXT (not fixed-width) so the **configurable** UTR pattern (seller_settings,
# task 3.5) can vary in length; it is globally UNIQUE across all orders (Req 6.4)
# but NULLABLE with SQL's "NULLs are distinct" semantics, so the many offline
# orders that never record a UTR can all coexist with a NULL ``utr``. The
# uniqueness is enforced by a dedicated UNIQUE index (``ix_payments_utr``). Only
# the object-storage *key* of an optional screenshot is stored here; the blob
# itself lives in the private bucket, never in the DB (Req 6.3).
# ---------------------------------------------------------------------------
class Payment(Base):
    """Per-order payment record with a globally-unique nullable UTR (Req 6)."""

    __tablename__ = "payments"
    __table_args__ = (
        # Global UTR uniqueness across orders; multiple NULLs allowed (NULLs are
        # distinct on both PostgreSQL and SQLite), so offline orders coexist.
        sa.Index("ix_payments_utr", "utr", unique=True),
    )

    payment_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    # One payment per order -> UNIQUE FK to orders (Req 6).
    order_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("orders.order_id"), nullable=False, unique=True
    )
    # Variable-length to support the configurable UTR pattern; globally unique
    # via ix_payments_utr; NULL until the customer submits a UTR (Req 6.4).
    utr: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    utr_submitted_at: Mapped[Optional[datetime]] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    # Object-storage reference only; the blob never lives in the DB (Req 6.3).
    screenshot_object_key: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


# ---------------------------------------------------------------------------
# Audit_Trail (task 3.3; design.md -> Data Models -> Audit_Trail; Req 15.12, 17.8).
#
# APPEND-ONLY. Rows are only ever INSERTed and SELECTed; they are never updated
# or deleted. The guarantee is enforced by **application policy plus database
# privileges**: in production the application's DB role is granted only
# INSERT/SELECT on this table (the migration emits those GRANTs on PostgreSQL
# when an ``-x app_role=...`` is supplied; see the migration). The ORM mapping
# below intentionally exposes no update/delete affordance beyond ordinary SQL.
# ``detail`` is a JSONB/JSON document of the shape
# ``{format_version, field, old_value, new_value}`` (additively versioned).
# ---------------------------------------------------------------------------
class AuditTrail(Base):
    """Append-only record of significant Seller actions on an order (Req 15.12)."""

    __tablename__ = "audit_trail"

    audit_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    order_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("orders.order_id"), nullable=False
    )
    action: Mapped[AuditAction] = mapped_column(
        _enum(AuditAction, AUDIT_ACTION_ENUM_NAME), nullable=False
    )
    # {format_version, field, old_value, new_value} (Req 13.7 additive payload).
    detail: Mapped[dict] = mapped_column(_json(), nullable=False)
    acting_user_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("users.user_id"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


# ---------------------------------------------------------------------------
# Notifications (task 3.3; design.md -> Data Models -> Notifications; Req 11).
#
# Delivery + bounded-retry queue. Enqueue is idempotent per
# ``(order_id, kind, transition_seq)`` (UNIQUE) so a retried transition never
# produces duplicate notifications (Req 11). The retry worker polls
# ``status IN (PENDING, FAILED) AND next_attempt_at <= now`` ordered by the
# ``(status, next_attempt_at)`` index. ``next_attempt_at`` defaults to now() so
# freshly-enqueued PENDING rows are immediately due. ``payload`` is a
# JSONB/JSON document carrying a ``format_version`` (Req 13.7).
# ---------------------------------------------------------------------------
class Notification(Base):
    """A queued, retry-able customer/Seller notification (Req 11.1-11.5)."""

    __tablename__ = "notifications"
    __table_args__ = (
        # Idempotent enqueue per order/kind/transition (Req 11).
        sa.UniqueConstraint("order_id", "kind", "transition_seq"),
        # Defense-in-depth: the retry budget counter is never negative.
        sa.CheckConstraint("attempts >= 0", name="attempts_non_negative"),
        # Retry-worker poll: due rows by status then schedule.
        sa.Index("ix_notifications_status_next_attempt_at", "status", "next_attempt_at"),
    )

    notification_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    order_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("orders.order_id"), nullable=False
    )
    recipient_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, sa.ForeignKey("users.user_id"), nullable=False
    )
    kind: Mapped[NotificationKind] = mapped_column(
        _enum(NotificationKind, NOTIFICATION_KIND_ENUM_NAME), nullable=False
    )
    # Monotonic per-order transition counter; part of the idempotency key.
    transition_seq: Mapped[int] = mapped_column(sa.Integer, nullable=False)
    # {format_version, ...} (Req 13.7 additive payload).
    payload: Mapped[dict] = mapped_column(_json(), nullable=False)
    status: Mapped[NotificationStatus] = mapped_column(
        _enum(NotificationStatus, NOTIFICATION_STATUS_ENUM_NAME),
        nullable=False,
        server_default=NotificationStatus.PENDING.value,
    )
    attempts: Mapped[int] = mapped_column(
        sa.SmallInteger, nullable=False, server_default=sa.text("0")
    )
    last_attempt_at: Mapped[Optional[datetime]] = mapped_column(
        sa.DateTime(timezone=True), nullable=True
    )
    # Defaults to now() so a new PENDING row is immediately due for delivery.
    next_attempt_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )


# ---------------------------------------------------------------------------
# Seller_Settings (task 3.5; design.md -> Data Models -> Seller_Settings;
# Req 6.2, 6.6, 19.1, 19.3, 19.5, 19.7).
#
# A SINGLE settings row owned by the Seller holding the operator-configurable
# values that were previously pure environment configuration (pickup location,
# UPI payee details, UPI QR reference, the configurable UTR pattern). Moving
# them here makes them editable at runtime through the Admin_Console (Req 19)
# without a redeploy; environment variables may still *seed* initial defaults.
#
# Singleton: enforced exactly like the ``meta`` table's ``CHECK (meta_id = 1)``
# pattern - a constant discriminator column ``singleton`` pinned to 1 by a CHECK
# and made UNIQUE, so at most one settings row can ever exist regardless of the
# UUID primary key. ``present_instructions`` / the pickup notification therefore
# always read the same authoritative row.
#
# Portability: ``upi_qr_object_key`` stores only an object-storage *reference*;
# the QR blob itself never lives in the DB (Req 19.5/19.6), mirroring
# ``payments.screenshot_object_key``. ``utr_pattern`` is variable-length TEXT
# with a server_default of exactly-12-alphanumeric (Req 6.2/6.6); the VPA in
# ``upi_address`` is validated at the service layer (task 20.2) - the column
# only stores it.
# ---------------------------------------------------------------------------
class SellerSettings(Base):
    """Single-row, Seller-owned operator settings (Req 19, 6.2/6.6)."""

    __tablename__ = "seller_settings"
    __table_args__ = (
        # Singleton guard mirroring ``meta``'s CHECK (meta_id = 1): the constant
        # discriminator is pinned to 1 and made UNIQUE so only one row exists.
        sa.CheckConstraint("singleton = 1", name="singleton"),
        sa.UniqueConstraint("singleton"),
        # pickup_location is NULL until set; when present it must be 1-500 chars
        # (Req 19.1/19.2).
        sa.CheckConstraint(
            "pickup_location IS NULL OR "
            "(length(pickup_location) >= 1 AND length(pickup_location) <= 500)",
            name="pickup_location_len",
        ),
    )

    seller_settings_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid, primary_key=True, default=uuid.uuid4
    )
    # Constant discriminator pinned to 1 (singleton guard); never user-facing.
    singleton: Mapped[int] = mapped_column(
        sa.SmallInteger, nullable=False, server_default=sa.text("1")
    )
    # Seller-defined collection address; NULL until set (Req 19.1/19.2, 19.9).
    pickup_location: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    # Payee VPA; NULL until set. VPA shape validated at the service layer.
    upi_address: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    # Object-storage reference to the uploaded UPI QR image; blob not in DB.
    upi_qr_object_key: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    # Configured UTR format; default = exactly 12 alphanumeric (Req 6.2/6.6).
    utr_pattern: Mapped[str] = mapped_column(
        sa.Text, nullable=False, server_default=sa.text(f"'{DEFAULT_UTR_PATTERN}'")
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
    )
    schema_version: Mapped[int] = mapped_column(
        sa.SmallInteger, nullable=False, server_default=sa.text("1")
    )


__all__ = [
    "Base",
    "Role",
    "Unit",
    "OrderState",
    "Language",
    "AuditAction",
    "NotificationKind",
    "NotificationStatus",
    "ROLE_VALUES",
    "UNIT_VALUES",
    "ORDER_STATE_VALUES",
    "LANGUAGE_VALUES",
    "AUDIT_ACTION_VALUES",
    "NOTIFICATION_KIND_VALUES",
    "NOTIFICATION_STATUS_VALUES",
    "ORDER_STATE_ENUM_NAME",
    "UNIT_ENUM_NAME",
    "ROLE_ENUM_NAME",
    "LANGUAGE_ENUM_NAME",
    "AUDIT_ACTION_ENUM_NAME",
    "NOTIFICATION_KIND_ENUM_NAME",
    "NOTIFICATION_STATUS_ENUM_NAME",
    "PRICE_MAX",
    "QUANTITY_MAX",
    "DEFAULT_UTR_PATTERN",
    "Meta",
    "User",
    "Category",
    "Product",
    "Cart",
    "CartItem",
    "Order",
    "OrderItem",
    "Payment",
    "AuditTrail",
    "Notification",
    "SellerSettings",
]
