"""Integration test for the carts/orders schema migration (task 3.2).

Applies migration ``0002_carts_orders`` (on top of ``0001_initial_schema``) to a
fresh database and asserts that:

  * the new tables (``carts``, ``cart_items``, ``orders``, ``order_items``)
    exist and accept a full valid customer -> cart -> order insert chain;
  * ``UNIQUE(cart_id, product_id)`` enforces combine-on-add (Req 4.5);
  * ``carts.customer_id`` is UNIQUE (one active cart per customer);
  * ``orders.order_number`` is UNIQUE (human-friendly id);
  * the foreign keys reject orphan rows;
  * the ``rejection_reason`` length bound (<=500) and the ``order_state`` enum
    are enforced;
  * the migration upgrades and downgrades cleanly (0002 removes only its own
    tables, leaving the 0001 tables intact), and ``alembic check`` reports no
    drift between ``Base.metadata`` and the migrated database.

As with the initial-schema test, the suite always runs against throwaway
**SQLite** and additionally against **PostgreSQL** when ``MARKETPLACE_TEST_PG_URL``
points at a reachable server. SQLite foreign-key enforcement is explicitly
enabled (it is off by default) so the FK assertions are meaningful.
"""

from __future__ import annotations

import os
import uuid
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

pytestmark = pytest.mark.integration

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Tables introduced by 0002; the 0001 tables must survive a downgrade to 0001.
NEW_TABLES = {"carts", "cart_items", "orders", "order_items"}
INITIAL_TABLES = {"meta", "users", "categories", "products"}


def _alembic_config(db_url: str) -> Config:
    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    cfg.set_main_option("sqlalchemy.url", db_url)
    return cfg


# ---------------------------------------------------------------------------
# Insert helpers (raw SQL so the test exercises the migrated schema directly).
# ---------------------------------------------------------------------------
def _new_user(conn: sa.Connection, telegram_user_id: int) -> str:
    uid = uuid.uuid4().hex
    conn.execute(
        sa.text(
            "INSERT INTO users (user_id, telegram_user_id, role) "
            "VALUES (:id, :tg, 'CUSTOMER')"
        ),
        {"id": uid, "tg": telegram_user_id},
    )
    return uid


def _new_category(conn: sa.Connection, name: str) -> str:
    cid = uuid.uuid4().hex
    conn.execute(
        sa.text("INSERT INTO categories (category_id, name) VALUES (:id, :name)"),
        {"id": cid, "name": name},
    )
    return cid


def _new_product(conn: sa.Connection, category_id: str) -> str:
    pid = uuid.uuid4().hex
    conn.execute(
        sa.text(
            "INSERT INTO products (product_id, name, category_id, unit, "
            "price_per_unit, min_order_quantity, stock_quantity) "
            "VALUES (:id, 'Cotton Seed Oil Cake', :c, 'KILOGRAM', 100.00, "
            "10.000, 500.000)"
        ),
        {"id": pid, "c": category_id},
    )
    return pid


def _new_cart(conn: sa.Connection, customer_id: str) -> str:
    cart_id = uuid.uuid4().hex
    conn.execute(
        sa.text("INSERT INTO carts (cart_id, customer_id) VALUES (:id, :cust)"),
        {"id": cart_id, "cust": customer_id},
    )
    return cart_id


def _add_cart_item(conn: sa.Connection, cart_id: str, product_id: str, qty="10.000"):
    conn.execute(
        sa.text(
            "INSERT INTO cart_items (cart_item_id, cart_id, product_id, quantity) "
            "VALUES (:id, :cart, :prod, :qty)"
        ),
        {"id": uuid.uuid4().hex, "cart": cart_id, "prod": product_id, "qty": qty},
    )


def _new_order(conn: sa.Connection, customer_id: str, order_number: int, **overrides):
    params = {
        "id": uuid.uuid4().hex,
        "num": order_number,
        "cust": customer_id,
        "state": "PAYMENT_PENDING",
        "total": "1000.00",
        "reason": None,
    }
    params.update(overrides)
    conn.execute(
        sa.text(
            "INSERT INTO orders (order_id, order_number, customer_id, state, "
            "total_amount, rejection_reason) "
            "VALUES (:id, :num, :cust, :state, :total, :reason)"
        ),
        params,
    )
    return params["id"]


def _add_order_item(conn: sa.Connection, order_id: str, product_id: str):
    conn.execute(
        sa.text(
            "INSERT INTO order_items (order_item_id, order_id, product_id, "
            "ordered_quantity, unit_price, line_amount) "
            "VALUES (:id, :order, :prod, 10.000, 100.00, 1000.00)"
        ),
        {"id": uuid.uuid4().hex, "order": order_id, "prod": product_id},
    )


# ---------------------------------------------------------------------------
# Backend fixtures
# ---------------------------------------------------------------------------
def _backends():
    params = [pytest.param("sqlite", id="sqlite")]
    if os.environ.get("MARKETPLACE_TEST_PG_URL"):
        params.append(pytest.param("postgresql", id="postgresql"))
    return params


def _enable_sqlite_fk(engine: sa.Engine) -> None:
    """SQLite does not enforce foreign keys unless asked to per-connection."""

    @sa.event.listens_for(engine, "connect")
    def _set_pragma(dbapi_connection, _record):  # pragma: no cover - trivial
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()


@pytest.fixture(params=_backends())
def db(request, tmp_path, monkeypatch):
    """Apply migrations to a fresh DB; yield (engine, cfg) for the backend."""
    if request.param == "sqlite":
        url = f"sqlite:///{tmp_path / 'carts_orders_test.db'}"
    else:
        url = os.environ["MARKETPLACE_TEST_PG_URL"]

    monkeypatch.setenv("DB_URL", url)
    cfg = _alembic_config(url)

    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")

    eng = sa.create_engine(url)
    if request.param == "sqlite":
        _enable_sqlite_fk(eng)
    try:
        yield eng, cfg
    finally:
        eng.dispose()
        command.downgrade(cfg, "base")


# ---------------------------------------------------------------------------
# Structure
# ---------------------------------------------------------------------------
def test_new_tables_exist(db):
    engine, _ = db
    tables = set(sa.inspect(engine).get_table_names())
    assert NEW_TABLES.issubset(tables), tables
    # The initial-schema tables must still be present after 0002.
    assert INITIAL_TABLES.issubset(tables), tables


def test_full_insert_chain_succeeds(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1001)
        category = _new_category(conn, "Oil Cakes")
        product = _new_product(conn, category)
        cart = _new_cart(conn, customer)
        _add_cart_item(conn, cart, product)
        order = _new_order(conn, customer, order_number=1)
        _add_order_item(conn, order, product)

    with engine.connect() as conn:
        assert conn.execute(sa.text("SELECT count(*) FROM cart_items")).scalar_one() == 1
        assert conn.execute(sa.text("SELECT count(*) FROM order_items")).scalar_one() == 1


# ---------------------------------------------------------------------------
# Uniqueness constraints
# ---------------------------------------------------------------------------
def test_cart_item_unique_cart_product_combine_on_add(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1002)
        category = _new_category(conn, "Cat A")
        product = _new_product(conn, category)
        cart = _new_cart(conn, customer)
        _add_cart_item(conn, cart, product)
    # A second line for the same (cart, product) violates UNIQUE (Req 4.5).
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _add_cart_item(conn, cart, product, qty="20.000")


def test_cart_one_per_customer_unique(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1003)
        _new_cart(conn, customer)
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _new_cart(conn, customer)


def test_order_number_unique(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1004)
        _new_order(conn, customer, order_number=42)
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _new_order(conn, customer, order_number=42)


# ---------------------------------------------------------------------------
# Foreign keys
# ---------------------------------------------------------------------------
def test_cart_item_requires_existing_cart(db):
    engine, _ = db
    with engine.begin() as conn:
        category = _new_category(conn, "Cat FK")
        product = _new_product(conn, category)
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _add_cart_item(conn, uuid.uuid4().hex, product)


def test_order_item_requires_existing_order(db):
    engine, _ = db
    with engine.begin() as conn:
        category = _new_category(conn, "Cat FK2")
        product = _new_product(conn, category)
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _add_order_item(conn, uuid.uuid4().hex, product)


def test_order_requires_existing_customer(db):
    engine, _ = db
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _new_order(conn, uuid.uuid4().hex, order_number=7)


# ---------------------------------------------------------------------------
# Check / enum constraints
# ---------------------------------------------------------------------------
def test_rejection_reason_length_constraint(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1005)
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _new_order(
                conn, customer, order_number=8, state="REJECTED", reason="x" * 501
            )


def test_rejection_reason_at_limit_allowed(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1006)
        _new_order(
            conn, customer, order_number=9, state="REJECTED", reason="x" * 500
        )


def test_order_state_enum_rejects_invalid(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1007)
    with engine.begin() as conn:
        with pytest.raises(sa.exc.IntegrityError):
            _new_order(conn, customer, order_number=10, state="NOT_A_STATE")


def test_order_schema_version_defaults_to_one(db):
    engine, _ = db
    with engine.begin() as conn:
        customer = _new_user(conn, 1008)
        order = _new_order(conn, customer, order_number=11)
        version = conn.execute(
            sa.text("SELECT schema_version FROM orders WHERE order_id = :id"),
            {"id": order},
        ).scalar_one()
    assert version == 1


# ---------------------------------------------------------------------------
# Migration round-trip and drift
# ---------------------------------------------------------------------------
def test_downgrade_to_initial_removes_only_new_tables(db):
    engine, cfg = db
    command.downgrade(cfg, "0001_initial_schema")
    tables = set(sa.inspect(engine).get_table_names())
    assert not (NEW_TABLES & tables), tables
    assert INITIAL_TABLES.issubset(tables), tables
    # Restore head so the fixture teardown's downgrade-to-base is consistent.
    command.upgrade(cfg, "head")


def test_alembic_check_reports_no_drift(db):
    engine, cfg = db
    # command.check raises AutogenerateDiffsDetected if Base.metadata and the
    # migrated database disagree; no exception means the migration matches.
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"Schema drift detected between models and migration: {exc}")
